runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START env_variables]
env_variables:
    MAILGUN_DOMAIN_NAME: sandboxf88ac31f30a3402ba6f8a965e6762bc4.mailgun.org
    MAILGUN_API_KEY: key-39077b242ae1a10181127e7ac117c4ee
# [END env_variables]
