runtime: python
env: flex

# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -b :$PORT -b :65080 -k flask_sockets.worker main:app

# We must use python 2 because flask-sockets depends on gevent which
# doesn't currently have Python 3 support.
runtime_config:
  python_version: 2

# [START network]
network:
  instance_tag: websocket
# [END network]
